// Raças de cachorro — arquivo COMPARTILHADO entre o app da Ju (index.html) e a
// página do cliente (agendar.html). É a única lista duplicada que virou arquivo
// próprio: são ~180 linhas, e manter duas cópias garantiria divergência.
//
// Cada raça traz o PORTE típico do adulto, que serve para dois usos:
//   1. preencher o porte sozinho ao escolher a raça (menos digitação);
//   2. o preço sair certo, já que a tabela é por porte.
//
// ⚠️ O porte aqui é SUGESTÃO — sempre editável. Um Poodle pode ser toy ou standard,
// um SRD pode ter qualquer tamanho, e filhote não tem o porte do adulto.
// Critério: Pequeno até ~10kg · Médio 10–25kg · Grande acima de 25kg.

const RACAS = [
  // sem raça definida vem primeiro, é o caso mais comum no balcão
  { n: 'SRD — Sem raça definida (vira-lata)', p: '' },
  { n: 'Não sei a raça',                      p: '' },

  { n: 'Affenpinscher',                    p: 'Pequeno' },
  { n: 'Airedale Terrier',                 p: 'Grande'  },
  { n: 'Akita Americano',                  p: 'Grande'  },
  { n: 'Akita Inu',                        p: 'Grande'  },
  { n: 'American Bully',                   p: 'Médio'   },
  { n: 'American Staffordshire Terrier',   p: 'Grande'  },
  { n: 'Basenji',                          p: 'Médio'   },
  { n: 'Basset Hound',                     p: 'Médio'   },
  { n: 'Beagle',                           p: 'Médio'   },
  { n: 'Bearded Collie',                   p: 'Grande'  },
  { n: 'Beauceron',                        p: 'Grande'  },
  { n: 'Bedlington Terrier',               p: 'Pequeno' },
  { n: 'Bichon Frisé',                     p: 'Pequeno' },
  { n: 'Bloodhound',                       p: 'Grande'  },
  { n: 'Bobtail (Old English Sheepdog)',   p: 'Grande'  },
  { n: 'Boerboel',                         p: 'Grande'  },
  { n: 'Boiadeiro Australiano',            p: 'Médio'   },
  { n: 'Boiadeiro Bernês',                 p: 'Grande'  },
  { n: 'Border Collie',                    p: 'Médio'   },
  { n: 'Border Terrier',                   p: 'Pequeno' },
  { n: 'Borzoi',                           p: 'Grande'  },
  { n: 'Boston Terrier',                   p: 'Pequeno' },
  { n: 'Bouvier de Flandres',              p: 'Grande'  },
  { n: 'Boxer',                            p: 'Grande'  },
  { n: 'Braco Alemão',                     p: 'Grande'  },
  { n: 'Briard',                           p: 'Grande'  },
  { n: 'Buldogue Americano',               p: 'Grande'  },
  { n: 'Buldogue Campeiro',                p: 'Grande'  },
  { n: 'Buldogue Francês',                 p: 'Médio'   },
  { n: 'Buldogue Inglês',                  p: 'Médio'   },
  { n: 'Bull Terrier',                     p: 'Médio'   },
  { n: 'Bull Terrier Miniatura',           p: 'Pequeno' },
  { n: 'Bullmastiff',                      p: 'Grande'  },
  { n: 'Cairn Terrier',                    p: 'Pequeno' },
  { n: 'Cane Corso',                       p: 'Grande'  },
  { n: 'Cão de Água Português',            p: 'Médio'   },
  { n: 'Cão de Crista Chinês',             p: 'Pequeno' },
  { n: 'Cavalier King Charles Spaniel',    p: 'Pequeno' },
  { n: 'Chihuahua',                        p: 'Pequeno' },
  { n: 'Chow Chow',                        p: 'Grande'  },
  { n: 'Cocker Spaniel Americano',         p: 'Médio'   },
  { n: 'Cocker Spaniel Inglês',            p: 'Médio'   },
  { n: 'Collie',                           p: 'Grande'  },
  { n: 'Corgi (Cardigan)',                 p: 'Médio'   },
  { n: 'Corgi (Pembroke)',                 p: 'Médio'   },
  { n: 'Coton de Tuléar',                  p: 'Pequeno' },
  { n: 'Dachshund (Teckel / Salsicha)',    p: 'Pequeno' },
  { n: 'Dálmata',                          p: 'Grande'  },
  { n: 'Doberman',                         p: 'Grande'  },
  { n: 'Dogo Argentino',                   p: 'Grande'  },
  { n: 'Dogue Alemão',                     p: 'Grande'  },
  { n: 'Dogue de Bordeaux',                p: 'Grande'  },
  { n: 'Elkhound Norueguês',               p: 'Médio'   },
  { n: 'Eurasier',                         p: 'Médio'   },
  { n: 'Fila Brasileiro',                  p: 'Grande'  },
  { n: 'Flat-Coated Retriever',            p: 'Grande'  },
  { n: 'Fox Paulistinha (Terrier Brasileiro)', p: 'Pequeno' },
  { n: 'Fox Terrier (Pelo Duro)',          p: 'Pequeno' },
  { n: 'Fox Terrier (Pelo Liso)',          p: 'Pequeno' },
  { n: 'Galgo Inglês (Greyhound)',         p: 'Grande'  },
  { n: 'Galgo Italiano',                   p: 'Pequeno' },
  { n: 'Golden Retriever',                 p: 'Grande'  },
  { n: 'Goldendoodle',                     p: 'Grande'  },
  { n: 'Grande Boiadeiro Suíço',           p: 'Grande'  },
  { n: 'Griffon de Bruxelas',              p: 'Pequeno' },
  { n: 'Havanês',                          p: 'Pequeno' },
  { n: 'Husky Siberiano',                  p: 'Grande'  },
  { n: 'Jack Russell Terrier',             p: 'Pequeno' },
  { n: 'Keeshond',                         p: 'Médio'   },
  { n: 'Kelpie Australiano',               p: 'Médio'   },
  { n: 'Kerry Blue Terrier',               p: 'Médio'   },
  { n: 'Komondor',                         p: 'Grande'  },
  { n: 'Kuvasz',                           p: 'Grande'  },
  { n: 'Labradoodle',                      p: 'Grande'  },
  { n: 'Labrador Retriever',               p: 'Grande'  },
  { n: 'Lagotto Romagnolo',                p: 'Médio'   },
  { n: 'Lakeland Terrier',                 p: 'Pequeno' },
  { n: 'Leonberger',                       p: 'Grande'  },
  { n: 'Lhasa Apso',                       p: 'Pequeno' },
  { n: 'Löwchen',                          p: 'Pequeno' },
  { n: 'Lulu da Pomerânia (Spitz Alemão)', p: 'Pequeno' },
  { n: 'Malamute do Alasca',               p: 'Grande'  },
  { n: 'Maltês',                           p: 'Pequeno' },
  { n: 'Maltipoo',                         p: 'Pequeno' },
  { n: 'Manchester Terrier',               p: 'Pequeno' },
  { n: 'Mastiff Inglês',                   p: 'Grande'  },
  { n: 'Mastim Napolitano',                p: 'Grande'  },
  { n: 'Mastim Tibetano',                  p: 'Grande'  },
  { n: 'Norfolk Terrier',                  p: 'Pequeno' },
  { n: 'Norwich Terrier',                  p: 'Pequeno' },
  { n: 'Papillon',                         p: 'Pequeno' },
  { n: 'Pastor Alemão',                    p: 'Grande'  },
  { n: 'Pastor Australiano',               p: 'Grande'  },
  { n: 'Pastor Belga Malinois',            p: 'Grande'  },
  { n: 'Pastor Branco Suíço',              p: 'Grande'  },
  { n: 'Pastor de Shetland',               p: 'Médio'   },
  { n: 'Pastor do Cáucaso',                p: 'Grande'  },
  { n: 'Pastor Maremano',                  p: 'Grande'  },
  { n: 'Pastor dos Pirineus',              p: 'Grande'  },
  { n: 'Pequinês',                         p: 'Pequeno' },
  { n: 'Petit Basset Griffon Vendéen',     p: 'Médio'   },
  { n: 'Pinscher Miniatura',               p: 'Pequeno' },
  { n: 'Pit Bull (American Pit Bull Terrier)', p: 'Médio' },
  { n: 'Podengo Português',                p: 'Médio'   },
  { n: 'Pointer Inglês',                   p: 'Grande'  },
  { n: 'Pomsky',                           p: 'Médio'   },
  { n: 'Poodle Anão (Miniatura)',          p: 'Pequeno' },
  { n: 'Poodle Médio',                     p: 'Médio'   },
  { n: 'Poodle Standard (Gigante)',        p: 'Grande'  },
  { n: 'Poodle Toy',                       p: 'Pequeno' },
  { n: 'Presa Canário',                    p: 'Grande'  },
  { n: 'Pug',                              p: 'Pequeno' },
  { n: 'Puli',                             p: 'Médio'   },
  { n: 'Rat Terrier',                      p: 'Pequeno' },
  { n: 'Rhodesian Ridgeback',              p: 'Grande'  },
  { n: 'Rottweiler',                       p: 'Grande'  },
  { n: 'Saluki',                           p: 'Grande'  },
  { n: 'Samoieda',                         p: 'Grande'  },
  { n: 'São Bernardo',                     p: 'Grande'  },
  { n: 'Schipperke',                       p: 'Pequeno' },
  { n: 'Schnauzer Gigante',                p: 'Grande'  },
  { n: 'Schnauzer Miniatura',              p: 'Pequeno' },
  { n: 'Schnauzer Standard',               p: 'Médio'   },
  { n: 'Schnoodle',                        p: 'Pequeno' },
  { n: 'Scottish Terrier',                 p: 'Pequeno' },
  { n: 'Sealyham Terrier',                 p: 'Pequeno' },
  { n: 'Setter Gordon',                    p: 'Grande'  },
  { n: 'Setter Irlandês',                  p: 'Grande'  },
  { n: 'Shar Pei',                         p: 'Médio'   },
  { n: 'Shiba Inu',                        p: 'Médio'   },
  { n: 'Shih Tzu',                         p: 'Pequeno' },
  { n: 'Silky Terrier',                    p: 'Pequeno' },
  { n: 'Skye Terrier',                     p: 'Pequeno' },
  { n: 'Soft Coated Wheaten Terrier',      p: 'Médio'   },
  { n: 'Spaniel Bretão',                   p: 'Médio'   },
  { n: 'Spinone Italiano',                 p: 'Grande'  },
  { n: 'Spitz Japonês',                    p: 'Pequeno' },
  { n: 'Springer Spaniel Inglês',          p: 'Médio'   },
  { n: 'Staffordshire Bull Terrier',       p: 'Médio'   },
  { n: 'Sussex Spaniel',                   p: 'Médio'   },
  { n: 'Terra Nova',                       p: 'Grande'  },
  { n: 'Terrier Tibetano',                 p: 'Médio'   },
  { n: 'Tosa Inu',                         p: 'Grande'  },
  { n: 'Vizsla',                           p: 'Grande'  },
  { n: 'Volpino Italiano',                 p: 'Pequeno' },
  { n: 'Weimaraner',                       p: 'Grande'  },
  { n: 'Welsh Terrier',                    p: 'Pequeno' },
  { n: 'West Highland White Terrier (Westie)', p: 'Pequeno' },
  { n: 'Whippet',                          p: 'Médio'   },
  { n: 'Yorkshire Terrier',                p: 'Pequeno' },

  // sempre por último: escape para o que não está na lista
  { n: 'Outra raça (digitar)',             p: '' }
];

// porte típico de uma raça ('' quando não dá para saber, como SRD)
function porteDaRaca(nome) {
  const r = RACAS.find(x => x.n === nome);
  return r ? r.p : '';
}

// preenche um <select> com a lista. `outraId` é o campo de texto que aparece
// quando a pessoa escolhe "Outra raça (digitar)".
function montarSelectRacas(selectId) {
  const sel = document.getElementById(selectId);
  if (!sel) return;
  sel.innerHTML = '<option value="">Selecione a raça...</option>' +
    RACAS.map(r => `<option value="${r.n}">${r.n}</option>`).join('');
}
